# shellcheck shell=bash
# CLIProxyAPI installer. Sourced by setup.sh.
# ── CLIProxyAPI ──────────────────────────────────────────────────────────────
# Bridges OAuth CLI subscriptions (Codex / Claude Code / Antigravity / Gemini
# CLI / Kimi / xAI) into OpenAI + Claude + Gemini compatible APIs on :8317.
# The release tarball's asset name embeds the version (no versionless
# "latest" alias), so the tag is resolved from the GitHub API; checksums.txt
# is published per release and the tarball is verified against it.
# Layout: $CLIPROXY_HOME/<binary+config.example.yaml+README> with the binary
# symlinked into XDG_BIN_HOME as 'cli-proxy-api'. A pre-existing config.yaml
# is NEVER overwritten — the example is only copied when no config exists.
cliproxy_arch() {
  case "$(uname -m)" in
    x86_64|amd64)   echo "amd64" ;;
    aarch64|arm64)  echo "aarch64" ;;
    *)              die "CLIProxyAPI: unsupported arch $(uname -m)" ;;
  esac
}

install_cliproxy() {
  step "CLIProxyAPI (CLI OAuth → API bridge)"
  need_cmd tar
  mkdir -p "$XDG_BIN_HOME" "$CLIPROXY_HOME"

  # Resolve the latest tag (asset names are version-embedded, so 'latest/download'
  # cannot be used). awk reads to EOF deliberately: `grep -m1` would close the
  # pipe early and pipefail then turns curl's SIGPIPE (23) into a hard failure.
  # Fallback: scrape the /releases/latest redirect if the API is rate-limited.
  local tag=""
  tag="$(curl -fsSL "https://api.github.com/repos/$CLIPROXY_REPO/releases/latest" 2>/dev/null \
        | awk -F'"' '/"tag_name"/{t=$4} END{print t}')" || true
  if [[ -z "$tag" ]]; then
    tag="$(curl -fsSLI -o /dev/null -w '%{url_effective}' "$CLIPROXY_RELEASE_BASE/latest" 2>/dev/null | sed 's|.*/tag/||')" || true
  fi
  [[ "$tag" == v* ]] || die "CLIProxyAPI: could not resolve the latest release tag (got '$tag')"
  local ver="${tag#v}"

  local arch asset url
  arch="$(cliproxy_arch)"
  asset="CLIProxyAPI_${ver}_linux_${arch}.tar.gz"
  url="$CLIPROXY_RELEASE_BASE/download/$tag/$asset"
  local tmp="$XDG_DATA_HOME/_cliproxy.tar.gz"
  local tmpdir="$XDG_DATA_HOME/_cliproxy-extract"

  echo "  Downloading $asset"
  curl -fsSL "$url" -o "$tmp" || die "CLIProxyAPI download failed: $url"

  # Verify against the release's checksums.txt (format "<sha>  <asset>").
  local sums="$XDG_DATA_HOME/_cliproxy-checksums" sha=""
  if curl -fsSL "$CLIPROXY_RELEASE_BASE/download/$tag/checksums.txt" -o "$sums" 2>/dev/null; then
    sha="$(awk -v a="$asset" '$2 == a {print $1}' "$sums")"
    rm -f "$sums"
  fi
  verify_sha256 "$tmp" "$sha" "CLIProxyAPI ($asset)"

  rm -rf "$tmpdir"; mkdir -p "$tmpdir"
  tar -xzf "$tmp" -C "$tmpdir"
  [[ -f "$tmpdir/cli-proxy-api" ]] || die "CLIProxyAPI archive is missing the 'cli-proxy-api' binary"

  rm -f "$CLIPROXY_HOME/cli-proxy-api"
  mv -f "$tmpdir/cli-proxy-api" "$CLIPROXY_HOME/cli-proxy-api"
  chmod +x "$CLIPROXY_HOME/cli-proxy-api"
  # Ship the example alongside the binary for reference, and generate a
  # MINIMAL, SAFE config.yaml on first install. Copying config.example.yaml
  # verbatim would be a footgun: its defaults bind every interface (host: "")
  # and carry literal placeholder keys that look configured. A pre-existing
  # config.yaml is NEVER touched (keys + OAuth logins live there).
  [[ -f "$CLIPROXY_HOME/config.example.yaml" ]] || cp -f "$tmpdir/config.example.yaml" "$CLIPROXY_HOME/config.example.yaml" 2>/dev/null || true
  if [[ ! -f "$CLIPROXY_HOME/config.yaml" ]]; then
    local gen_key gen_secret
    if command -v openssl >/dev/null 2>&1; then
      gen_key="$(openssl rand -hex 24)"; gen_secret="$(openssl rand -hex 16)"
    else
      gen_key="$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
      gen_secret="$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    fi
    cat > "$CLIPROXY_HOME/config.yaml" <<YAML
# CLIProxyAPI config — generated by setup.sh (--cliproxy).
# Full option reference: config.example.yaml next to this file.
config-version: 8

server:
  host: "127.0.0.1"   # local-only; set "" to expose on all interfaces
  port: 8317

management:
  allow-remote: false
  secret-key: "$gen_secret"   # management API / control panel login
  disable-control-panel: false

access:
  api-keys:                          # client auth for the proxy endpoints
    - "$gen_key"

oauth:
  auth-dir: "$CLIPROXY_HOME/auths"   # OAuth credential JSONs land here
YAML
    chmod 600 "$CLIPROXY_HOME/config.yaml"
    warn "config.yaml generated (client key + management secret set; keys in the file)"
  fi

  # Persistence guard: pin oauth.auth-dir inside $CLIPROXY_HOME. The upstream
  # default is "~/.cli-proxy-api" — under $HOME, which Replit WIPES on
  # recreate, so a completed OAuth login would silently vanish. Only rewrites
  # when the value is exactly that volatile default (a user-chosen path is
  # left alone); copies, never moves, any existing creds.
  cliproxy_pin_authdir
  rm -rf "$tmpdir" "$tmp"

  ln -sfn "$CLIPROXY_HOME/cli-proxy-api" "$XDG_BIN_HOME/cli-proxy-api"
  ok "CLIProxyAPI installed: $CLIPROXY_HOME/cli-proxy-api ($("$CLIPROXY_HOME/cli-proxy-api" --help 2>&1 | head -1))"
  ok "  CLI: cli-proxy-api --config $CLIPROXY_HOME/config.yaml   (API on http://127.0.0.1:8317)"
  ok "  OAuth login (remote-safe): cli-proxy-api -codex-login -no-browser  |  -claude-login / -antigravity-login / -kimi-login / -xai-login"
  record_tool_env_vars CLIPROXY_HOME
  record_tool_path_dirs "$XDG_BIN_HOME" "$CLIPROXY_HOME"
  wire_tool cliproxy CLIPROXY_HOME -- "$XDG_BIN_HOME" "$CLIPROXY_HOME"
}
