# shellcheck shell=bash
# Hermes bundled Chromium — portable lib closure + launcher.
# Sourced by setup.sh.
#
# WHY: Hermes stages a Chrome-for-Testing build under $HERMES_HOME/tools/
# chromium-<N>/chrome-linux64/chrome. That binary is NOT self-contained on
# Replit — it has no RUNPATH for its nspr/nss/xkbcommon/gbm deps, so a bare
# invocation dies with
#   error while loading shared libraries: libnspr4.so: cannot open shared
#   object file
# and picking the WRONG /nix/store copy (32-bit) dies with
#   wrong ELF class: ELFCLASS32.
#
# The paths are NOT portable: the hash in /nix/store/<pkg>-<ver>-<hash> differs
# per machine and per nixpkgs revision. So this module resolves the closure at
# install time via resolve-libs.sh (soname -> nixpkgs attr -> store root) and
# writes it under a persistent XDG dir — never a hardcoded path. Same approach
# the camofox lane uses for its GTK closure.
#
# Consumers that cannot source a snippet (workflows, Run button, cron) get a
# launcher shim on PATH, exactly like launch-camofox-browser.

HERMES_CHROME_STATE="${XDG_CONFIG_HOME:-$HOME/.config}/hermes-chromium"
HERMES_CHROME_CLOSURE="$HERMES_CHROME_STATE/closure.txt"
HERMES_CHROME_ENVSNIP="$HERMES_CHROME_STATE/env.sh"

# Locate the staged chrome binary (version dir changes between Hermes builds).
hermes_chrome_bin() {
  local d
  for d in "$HERMES_HOME"/tools/chromium-*/chrome-linux64/chrome \
           "$HERMES_HOME"/tools/chromium-*/chrome-linux/chrome; do
    [[ -x "$d" ]] && { printf '%s' "$d"; return 0; }
  done
  return 1
}

hermes_chrome_write_env() {
  local bin="$1"
  mkdir -p "$HERMES_CHROME_STATE" || return 0
  {
    echo "# Hermes Chromium runtime env (setup.sh --hermes-browser). Source before chrome."
    echo "export LD_LIBRARY_PATH=\"\$(cat \"$HERMES_CHROME_CLOSURE\")\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}\""
    echo "export AGENT_BROWSER_EXECUTABLE_PATH=\"$bin\""
  } > "$HERMES_CHROME_ENVSNIP"
  ok "hermes-chromium env snippet: $HERMES_CHROME_ENVSNIP"
}

hermes_chrome_write_launcher() {
  local f="$XDG_BIN_HOME/launch-hermes-chrome"
  mkdir -p "$XDG_BIN_HOME" || return 0
  cat > "$f" <<EOF
#!/usr/bin/env bash
# Generated by setup.sh (--hermes-browser / --fix). Re-run --fix to refresh.
# Applies the resolved lib closure then execs the staged Hermes Chromium.
set -uo pipefail
ENVSH="$HERMES_CHROME_ENVSNIP"
[[ -s "\$ENVSH" ]] || { echo "launch-hermes-chrome: run 'bash setup.sh --hermes-browser' first" >&2; exit 1; }
. "\$ENVSH"
exec "\$AGENT_BROWSER_EXECUTABLE_PATH" "\$@"
EOF
  chmod +x "$f"
  ok "hermes-chromium launcher shim: $f"
}

install_hermes_chromium() {
  step "Hermes Chromium (portable lib closure)"
  local bin
  if ! bin="$(hermes_chrome_bin)"; then
    warn "no staged Hermes Chromium under $HERMES_HOME/tools/chromium-*/ — run 'hermes tools' first"
    return 0
  fi
  echo "  chrome: $bin"
  mkdir -p "$HERMES_CHROME_STATE"

  # Resolve on THIS machine (never copy a store path between hosts).
  if bash "$SCRIPT_DIR/setup/resolve-libs.sh" "$HERMES_CHROME_CLOSURE" chromium; then
    ok "closure resolved: $HERMES_CHROME_CLOSURE ($(tr ':' '\n' < "$HERMES_CHROME_CLOSURE" | grep -c .) lib dirs)"
  else
    warn "closure resolution failed — a bare chrome will not start; install nspr/nss/libxkbcommon/mesa"
    return 0
  fi

  hermes_chrome_write_env "$bin"
  hermes_chrome_write_launcher
  record_tool_path_dirs "$XDG_BIN_HOME"
  wire_tool hermes-chromium -- "$XDG_BIN_HOME"
  ok "hermes-chromium ready — run: launch-hermes-chrome --version"
}

clean_hermes_chromium() {
  _present "$HERMES_CHROME_STATE" "$XDG_BIN_HOME/launch-hermes-chrome" || { nothing_removed "Hermes Chromium closure"; return 0; }
  step "Removing Hermes Chromium closure"
  rm -rf "$HERMES_CHROME_STATE" "$XDG_BIN_HOME/launch-hermes-chrome"
  ok "Hermes Chromium closure removed (the browser itself is Hermes-managed; untouched)"
}